---
apiVersion: v1
kind: Service
metadata:
  name: spring-hello-world-service
  labels:
    app: spring-hello-world
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: "http"
      nodePort: 30020
      protocol: TCP
  selector:
    app: spring-hello-world
